with a as (select *
from {{ source('ga_analytics', 'airbyte_ingest') }})

--picking relevant fields from raw ingestion

select  DATE,
    FULLVISITORID AS USER_ID,
    CONCAT(FULLVISITORID, VISITID) AS SESSION_ID,
    VISITID AS SESSION_ID_key,

    CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', TO_TIMESTAMP_NTZ(VISITSTARTTIME)) AS SESSION_START_TIME,
    VISITNUMBER,
    PAGEVIEWS AS SESSION_PAGEVIEWS,
    HITS AS SESSION_HITS,
    BOUNCES AS SESSION_BOUNCES,
    SOURCE,
    MEDIUM,
    CAMPAIGN,
    KEYWORD,
    ISTRUEDIRECT as IS_TRUE_DIRECT,
    DEVICECATEGORY,
    COUNTRY,
    SUBCONTINENT,
    CONTINENT,
    PAGETITLE,
    CONTENTGROUP1,
    CONTENTGROUP2,
    HITNUMBER,
    HIT_TYPE,
    CONVERT_TIMEZONE(
        'UTC',
        'America/Los_Angeles',
        TIMESTAMPADD(
            SECOND,
            TRY_TO_NUMBER(hit_time) / 1000,
            TO_TIMESTAMP_NTZ(TRY_TO_NUMBER(visitStartTime))
        )
    ) AS hit_timestamp,
    TRANSACTIONS AS TRANSACTION_COUNT,
    TOTALTRANSACTIONREVENUE AS TOTAL_TRANSACTION_REVENUE,
    TOTALTRANSACTIONREVENUE / 1000000.0 AS TRANSACTION_REVENUE_ACTUAL,
    TRANSACTIONID,
       HIT_TRANSACTION_REVENUE / 1000000.0 AS HIT_TRANSACTION_REVENUE_ACTUAL,
    PRODUCT_ISIMPRESSION,
    ACTION_TYPE AS EVENT_ACTION_TYPE,
    EVENTCATEGORY AS EVENT_CATEGORY,
    EVENTACTION AS EVENT_ACTION,
    EVENTLABEL AS EVENT_LABEL,
    ISINTERACTION AS IS_INTERACTION,
    PRODUCT_NAME,
    PRODUCT_CATEGORY,
    PRODUCT_REVENUE,
    PRODUCT_ID,
    PRODUCT_QUANTITY
from a